version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: unless-stopped
    
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-myapp}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
      
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
      
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - ./postgres-init:/docker-entrypoint-initdb.d
      - ./postgres.conf:/etc/postgresql/postgresql.conf:ro
      
    command: >
      postgres 
      -c config_file=/etc/postgresql/postgresql.conf
      -c log_statement=all
      -c log_destination=stderr
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-myapp}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
      
    networks:
      - postgres_network
      
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # Opcional: pgAdmin para administración web
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@localhost}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      
    ports:
      - "${PGADMIN_PORT:-8080}:80"
      
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      
    depends_on:
      postgres:
        condition: service_healthy
        
    networks:
      - postgres_network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  postgres_network:
    driver: bridge
