services:
  postgres:
    image: postgres:17-alpine
    container_name: homelab_postgres
    restart: unless-stopped
    network_mode: host
    
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-homelab}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
      
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - ./postgres.conf:/etc/postgresql/postgresql.conf:ro
      
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
      
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.3'
        reservations:
          memory: 128M
          cpus: '0.1'

volumes:
  postgres_data:
    driver: local
