services:
  seanime:
    image: coyann/seanime
    container_name: seanime
    ports:
      - "3001:8080"      # Seanime UI
      - "3002:8081"      # qBittorrent UI
      - "6881:6881/tcp"  # Bittorrent TCP
      - "6881:6881/udp"  # Bittorrent UDP (trackers, DHT)
    volumes:
      - ./data:/data
      - ./config:/config
    restart: unless-stopped