version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"  # Exponemos el puerto en la red local
    environment:
      # Configuración básica
      - N8N_PORT=5678
      - N8N_PROTOCOL=http  # Usaremos http internamente, NPM manejará SSL
      - NODE_ENV=production
      - GENERIC_TIMEZONE=America/Bogota  # Ajusta a tu zona horaria
      
      # Configuración de base de datos (opcional pero recomendado para producción)
      # Si no lo configuras, n8n usará SQLite por defecto
      # - DB_TYPE=postgresdb
      # - DB_POSTGRESDB_DATABASE=n8n
      # - DB_POSTGRESDB_HOST=postgres
      # - DB_POSTGRESDB_PORT=5432
      # - DB_POSTGRESDB_USER=n8n
      # - DB_POSTGRESDB_PASSWORD=n8n_password
      
      # Configuración de webhooks
      # Ajusta estos valores según tu dominio si lo expones a internet
      - WEBHOOK_URL=http://localhost:5678/  # Cambia si usas dominio externo
      - N8N_HOST=localhost  # Cambia si usas dominio externo
      
      # Seguridad (opcional)
      # - N8N_BASIC_AUTH_ACTIVE=true
      # - N8N_BASIC_AUTH_USER=admin
      # - N8N_BASIC_AUTH_PASSWORD=tu_password_seguro
      
      # Configuración adicional
      - N8N_METRICS=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=true
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=168  # Mantener ejecuciones por 7 días
      - N8N_SECURE_COOKIE=false  # Desactivar cookies seguras para acceso local
      
    volumes:
      - n8n_data:/home/node/.n8n
      - ./files:/files  # Para archivos locales si los necesitas
    networks:
      - n8n_network
    # healthcheck:
    #   test: ["CMD", "wget", "--spider", "-q", "http://localhost:5678/healthz"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  # Opcional: PostgreSQL para mejor rendimiento en producción
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: n8n_postgres
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_USER=n8n
  #     - POSTGRES_PASSWORD=n8n_password
  #     - POSTGRES_DB=n8n
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - n8n_network

networks:
  n8n_network:
    driver: bridge

volumes:
  n8n_data:
  # postgres_data:
